#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Twist

def talker():
      pub = rospy.Publisher('move', Twist, queue_size=10)
      rospy.init_node('talker', anonymous = True)
      twist = Twist()

      target_linear_vel   = 0.0
      target_angular_vel  = 0.0
    
      target_linear_vel = 0.05
      
      twist.linear.x = target_linear_vel; twist.linear.y = 0.0; twist.linear.z = 0.0
      twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = target_angular_vel

      #method 2
      #rospy.loginfo(target_linear_vel)                        
      #pub.publish(twist)

      #method 1
      while not rospy.is_shutdown(): # ctrl+C: shutdown
            rospy.loginfo(twist)
            pub.publish(twist)
            #rospy.sleep(2)
      
      rospy.spin()

if __name__=='__main__':
      talker()